name: Package and Release Addon

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetches full history so changelog generation works properly

      - name: Extract Latest Release Notes
        run: |
          awk '/^## v[0-9]/{if(found) exit; found=1} found' CHANGELOG.md > RELEASE_NOTES.md

      - name: Package and Publish Addon
        uses: BigWigsMods/packager@v2.5.1
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          GITHUB_OAUTH: ${{ github.token }}
